import 'package:flutter/material.dart';
import 'package:gradient_borders/box_borders/gradient_box_border.dart';
import 'package:iv_project_invitation_theme/iv_project_invitation_theme.dart';
import 'package:iv_project_invitation_theme/src/page_types/page_view_with_bottom_tab_bar.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/page_view_based.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_cover_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_eighth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_fifth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_first_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_fourth_different_location_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_fourth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_second_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_seventh_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_sixth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_third_different_location_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_third_page.dart';
import 'package:iv_project_invitation_theme/src/widgets/bubble_background.dart';
import 'package:iv_project_invitation_theme/src/widgets/particle_sphere.dart';
import 'package:iv_project_model/iv_project_model.dart';
import 'package:quick_dev_sdk/quick_dev_sdk.dart';

class ElegantGreenMatchaGlass extends StatelessWidget {
  const ElegantGreenMatchaGlass({
    super.key,
    this.heightAdjustment = 0,
    this.initialPage = 0,
    required this.useWrapper,
    required this.viewAsSinglePage,
    required this.noAnimate,
    required this.viewType,
    required this.invitationId,
    required this.invitationData,
    this.imagesRaw,
    required this.brandProfile,
  });

  final double heightAdjustment;
  final int initialPage;
  final bool useWrapper;
  final bool viewAsSinglePage;
  final bool noAnimate;
  final ViewType viewType;
  final String invitationId;
  final InvitationDataResponse invitationData;
  final ImagesRaw? imagesRaw;
  final BrandProfileResponse brandProfile;

  @override
  Widget build(BuildContext context) {
    return PageViewBased(
      configs: PageViewBasedConfigs(
        tabConfig: TabConfig(
          useGlassEffect: true,
          indicatorColor: Colors.green.shade50,
          backgroundColor: ColorConverter.darken(Colors.green.shade900, 50),
          titleActiveColor: Colors.white,
          titleInactiveColor: Colors.green.shade200,
          iconActiveColor: Colors.white,
          iconInactiveColor: Colors.green.shade200,
        ),
        globalBackgroundsBuilder: () => [
          BubbleBackground(
            backgroundColor: ColorConverter.darken(Colors.green.shade100, 20).withValues(alpha: .6),
            bubbleColor1: ColorConverter.darken(Colors.lightGreenAccent, 15),
            bubbleColor2: ColorConverter.darken(Colors.green.shade900, 40),
            bubbleColor3: ColorConverter.darken(Colors.green.shade700, 40),
            bubbleColor4: ColorConverter.darken(Colors.green.shade400, 5),
            bubbleColor5: ColorConverter.darken(Colors.lightGreenAccent, 10),
            noAnimate: noAnimate,
          ),
        ],
        particleSphere: ParticleSphereConfig(
          particleVariatios: [
            Particle.circle(color: ColorConverter.darken(Colors.lightGreenAccent, 5)),
            Particle.circle(color: Colors.white),
            Particle.circle(color: ColorConverter.darken(Colors.green.shade700, 40)),
          ],
        ),
        coverPageConfig: PageViewBasedCoverPageConfig(
          gradientBaseColor: ColorConverter.darken(Colors.green.shade700, 60),
          brideNameColor: Colors.green.shade200,
          groomNameColor: Colors.green.shade200,
          countdownBorderWidth: 1,
          countdownOddColor: Colors.white.withValues(alpha: .15),
          countdownEvenColor: Colors.white.withValues(alpha: .15),
          countdownOddBorderColor: Colors.green.shade200,
          countdownEvenBorderColor: Colors.green.shade200,
          countdownNumberColor: Colors.green.shade50,
          countdownUnitColor: Colors.green.shade50,
          useLightningEffectOnCountdown: true,
          firstArrowColor: Colors.green.shade100.withValues(alpha: .7),
          secondArrowColor: Colors.green.shade300.withValues(alpha: .5),
        ),
        firstPageConfig: PageViewBasedFirstPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60),
          secondGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60).withValues(alpha: .0),
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .5,
          titlePageColor: Colors.white,
          openingTextColor: Colors.white,
          generalTextColor: ColorConverter.darken(Colors.green.shade700, 30),
          firstSubScaffoldColor: Colors.white.withValues(alpha: .4),
          firstSubScaffoldBorderColor: Colors.white.withValues(alpha: .7),
          firstSubScaffoldBorderWidth: 1,
          secondSubScaffoldColor: Colors.white.withValues(alpha: .3),
          secondSubScaffoldBorderColor: Colors.white.withValues(alpha: .7),
          secondSubScaffoldBorderWidth: 1,
        ),
        secondPageConfig: PageViewBasedSecondPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .3),
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .6,
          titlePageColor: ColorConverter.darken(Colors.green.shade900, 20),
          generalTextColor: ColorConverter.darken(Colors.green.shade500, 5),
          brideDividingBorderWidth: 1,
          brideImageBorderWidth: 1,
          brideDividingLineWidth: 1,
          brideDividingBorderColor: Colors.green.shade400,
          brideImageFrameColor: ColorConverter.darken(Colors.green.shade400, 5).withValues(alpha: .3),
          brideImageFrameBorderColor: ColorConverter.darken(Colors.green.shade400, 5).withValues(alpha: .8),
          brideDividingLineColor: Colors.green.shade400,
          brideNameTextColor: ColorConverter.darken(Colors.green.shade700),
          brideFatherNameTextColor: ColorConverter.darken(Colors.green.shade700),
          brideMotherNameTextColor: ColorConverter.darken(Colors.green.shade700),
          groomDividingBorderWidth: 1,
          groomImageBorderWidth: 1,
          groomDividingLineWidth: 1,
          groomDividingBorderColor: Colors.green.shade400,
          groomImageFrameColor: ColorConverter.darken(Colors.green.shade400, 5).withValues(alpha: .3),
          groomImageFrameBorderColor: ColorConverter.darken(Colors.green.shade400, 5).withValues(alpha: .8),
          groomDividingLineColor: Colors.green.shade400,
          groomNameTextColor: ColorConverter.darken(Colors.green.shade700),
          groomFatherNameTextColor: ColorConverter.darken(Colors.green.shade700),
          groomMotherNameTextColor: ColorConverter.darken(Colors.green.shade700),
        ),
        thirdPageConfig: PageViewBasedThirdPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60).withValues(alpha: .0),
          secondGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60),
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .7),
          stopsGradientScaffoldColor: [.0, .5],
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .5,
          titlePageColor: ColorConverter.darken(Colors.green.shade900, 20),
          contractTitleColor: ColorConverter.darken(Colors.green.shade700),
          contractBaseTextColor: ColorConverter.darken(Colors.green.shade700),
          receptionTitleColor: ColorConverter.darken(Colors.green.shade700),
          receptionBaseTextColor: ColorConverter.darken(Colors.green.shade700),
          dividingLineWidth: 1,
          dividingLineColor: Colors.green.shade300,
          contractCountdownBorderWidth: 1,
          contractCountdownOddColor: Colors.white.withValues(alpha: .3),
          contractCountdownEvenColor: Colors.white.withValues(alpha: .3),
          contractCountdownOddBorderColor: Colors.green.shade500,
          contractCountdownEvenBorderColor: Colors.green.shade500,
          contractCountdownNumberColor: ColorConverter.darken(Colors.green.shade700),
          contractCountdownUnitColor: ColorConverter.darken(Colors.green.shade700),
          receptionCountdownBorderWidth: 1,
          receptionCountdownOddColor: Colors.white.withValues(alpha: .4),
          receptionCountdownEvenColor: Colors.white.withValues(alpha: .4),
          receptionCountdownOddBorderColor: Colors.green.shade500,
          receptionCountdownEvenBorderColor: Colors.green.shade500,
          receptionCountdownNumberColor: ColorConverter.darken(Colors.green.shade700),
          receptionCountdownUnitColor: ColorConverter.darken(Colors.green.shade700),
          useLightningEffectOnCountdown: true,
        ),
        thirdDifferentLocationPageConfig: PageViewBasedThirdDifferentLocationPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60).withValues(alpha: .0),
          secondGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60),
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .7),
          stopsGradientScaffoldColor: [.0, .5],
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .5,
          titlePageColor: ColorConverter.darken(Colors.green.shade900, 20),
          dateTimeIconColor: ColorConverter.darken(Colors.green.shade700),
          dateTimeBaseTextColor: ColorConverter.darken(Colors.green.shade700),
          countdownBorderWidth: 1,
          countdownOddColor: Colors.white.withValues(alpha: .3),
          countdownEvenColor: Colors.white.withValues(alpha: .3),
          countdownOddBorderColor: Colors.green.shade500,
          countdownEvenBorderColor: Colors.green.shade500,
          countdownNumberColor: ColorConverter.darken(Colors.green.shade700),
          countdownUnitColor: ColorConverter.darken(Colors.green.shade700),
          useLightningEffectOnCountdown: false,
          dividingLineWidth: 1,
          dividingLineColor: ColorConverter.darken(Colors.green.shade500),
          placeIconColor: ColorConverter.darken(Colors.green.shade700),
          placeBaseTextColor: ColorConverter.darken(Colors.green.shade700),
          addressTextColor: ColorConverter.darken(Colors.green.shade700),
          mapsBorderColor: Colors.white.withValues(alpha: .7),
          getDirectionsButtonColor: ColorConverter.darken(Colors.green.shade500).withValues(alpha: .8),
          getDirectionsButtonLabelColor: Colors.white,
          getDirectionsButtonBorderWidth: 1.5,
          getDirectionsButtonBorderColor: Colors.white,
        ),
        fourthPageConfig: PageViewBasedFourthPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60),
          secondGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60).withValues(alpha: .0),
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .4),
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .5,
          titlePageColor: Colors.white,
          placeIconColor: Colors.white,
          placeTextColor: Colors.white,
          addressTextColor: Colors.white,
          dividingLineWidth: 1,
          dividingLineColor: Colors.white,
          mapsBorderColor: Colors.white.withValues(alpha: .7),
          getDirectionsButtonColor: ColorConverter.darken(Colors.green.shade500).withValues(alpha: .8),
          getDirectionsButtonLabelColor: Colors.white,
          getDirectionsButtonBorderWidth: 1.5,
          getDirectionsButtonBorderColor: Colors.white,
        ),
        fourthDifferentLocationPageConfig: PageViewBasedFourthDifferentLocationPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60),
          secondGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60).withValues(alpha: .0),
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .4),
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .5,
          titlePageColor: Colors.white,
          dateTimeIconColor: Colors.white,
          dateTimeBaseTextColor: Colors.white,
          countdownBorderWidth: 1,
          countdownOddColor: ColorConverter.lighten(Colors.green.shade50, 40).withValues(alpha: .6),
          countdownEvenColor: ColorConverter.lighten(Colors.green.shade50, 40).withValues(alpha: .6),
          countdownOddBorderColor: Colors.white,
          countdownEvenBorderColor: Colors.white,
          countdownNumberColor: ColorConverter.darken(Colors.green.shade700),
          countdownUnitColor: ColorConverter.darken(Colors.green.shade700),
          useLightningEffectOnCountdown: false,
          dividingLineWidth: 1,
          dividingLineColor: Colors.white,
          placeIconColor: Colors.white,
          placeBaseTextColor: Colors.white,
          addressTextColor: Colors.white,
          mapsBorderColor: Colors.white.withValues(alpha: .7),
          getDirectionsButtonColor: ColorConverter.darken(Colors.green.shade500).withValues(alpha: .8),
          getDirectionsButtonLabelColor: Colors.white,
          getDirectionsButtonBorderWidth: 1.5,
          getDirectionsButtonBorderColor: Colors.white,
        ),
        fifthPageConfig: PageViewBasedFifthPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .4),
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .6,
          titlePageColor: ColorConverter.darken(Colors.green.shade900, 20),
          dividingLineWidth: 1,
          dividingVerticalLineColor: ColorConverter.darken(Colors.green.shade200),
          dividingHorizontalLineColor: ColorConverter.darken(Colors.green.shade200),
          seeMoreButtonColor: ColorConverter.darken(Colors.green.shade500).withValues(alpha: .8),
          seeMoreButtonLabelColor: Colors.white,
          seeMoreButtonBorderWidth: 1.5,
          seeMoreButtonBorderColor: Colors.white,
          bottomSheetHandleColor: Colors.white,
          bottomSheetContentScaffoldColor: Colors.white.withValues(alpha: .8),
          bottomSheetBackgroundColor: ColorConverter.darken(Colors.green.shade900, 50).withValues(alpha: .8),
          bottomSheetCloseIconColor: Colors.white,
          bottomSheetOnHoverCloseIconColor: Colors.green.shade400,
        ),
        sixthPageConfig: PageViewBasedSixthPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60).withValues(alpha: 0),
          secondGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60),
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .5),
          stopsGradientScaffoldColor: [.0, .5],
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .5,
          titlePageColor: ColorConverter.darken(Colors.green.shade900, 20),
          introductionTextColor: ColorConverter.darken(Colors.green.shade700),
          introductionColor: Colors.white.withValues(alpha: .3),
          introductionBorderColor: Colors.white,
          introductionBorderWidth: 1,
          bankColor: Colors.white.withValues(alpha: .4),
          bankBorderColor: Colors.white,
          bankBorderWidth: 1,
          bankTextColor: ColorConverter.darken(Colors.green.shade700),
          bankCopyBaseColor: ColorConverter.darken(Colors.green.shade500),
        ),
        seventhPageConfig: PageViewBasedSeventhPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60),
          secondGradientBackgroundColor: ColorConverter.darken(Colors.green.shade700, 60).withValues(alpha: 0),
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .5),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .2),
          stopsGradientScaffoldColor: [.5, 1],
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .5,
          titlePageColor: Colors.white,
          fieldTextColor: Colors.white,
          fieldLabelColor: Colors.white,
          fieldFillColor: Colors.green.shade700.withValues(alpha: .2),
          fieldBorderColor: Colors.white,
          fieldSplashColor: Colors.white.withValues(alpha: .5),
          overlayColor: Colors.white.withValues(alpha: .9),
          overlayBorderColor: Colors.white,
          dropdownItemSelectedColor: Colors.green.shade200,
          dropdownItemTextColor: Colors.green.shade700,
          dropdownItemSelectedTextColor: Colors.white,
          dropdownItemHoveredColor: Colors.grey.shade100,
          dropdownItemSplashColor: Colors.grey.shade100,
          submitButtonColor: ColorConverter.darken(Colors.green.shade500).withValues(alpha: .8),
          submitButtonLabelColor: Colors.white,
          submitButtonBorderWidth: 1.5,
          submitButtonBorderColor: Colors.white,
          rsvpBackgroundColor: Colors.white.withValues(alpha: .8),
          rsvpBorderColor: Colors.white,
          rsvpNameTextColor: ColorConverter.darken(Colors.green.shade700),
          rsvpTimeAgoTextColor: Colors.grey.shade800,
          rsvpNameInstanceTextColor: Colors.grey.shade600,
          rsvpAttendanceTextColorLighten: 20,
          rsvpMessageTextColor: ColorConverter.darken(Colors.green.shade600),
          seeMoreButtonColor: ColorConverter.darken(Colors.green.shade500).withValues(alpha: .8),
          seeMoreButtonLabelColor: Colors.white,
          seeMoreButtonBorderWidth: 1.5,
          seeMoreButtonBorderColor: Colors.white,
          bottomSheetHandleColor: Colors.white,
          bottomSheetContentScaffoldColor: Colors.white.withValues(alpha: .9),
          bottomSheetBackgroundColor: ColorConverter.darken(Colors.green.shade900, 50).withValues(alpha: .8),
          bottomSheetCloseIconColor: Colors.white,
          bottomSheetOnHoverCloseIconColor: Colors.green.shade300,
        ),
        eighthPageConfig: PageViewBasedEighthPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientScaffoldColor: Colors.white.withValues(alpha: .3),
          secondGradientScaffoldColor: Colors.white.withValues(alpha: .3),
          scaffoldBorder: GradientBoxBorder(
            width: 1.5,
            gradient: LinearGradient(
              begin: .topLeft,
              end: .bottomRight,
              colors: [
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
                Colors.white.withValues(alpha: .2),
                Colors.white,
              ],
              transform: const GradientRotation(-0.2),
            ),
          ),
          useGlassEffectOnScaffold: true,
          glassEffectOpacity: .6,
          titlePageColor: ColorConverter.darken(Colors.green.shade900, 20),
          closingTextColor: ColorConverter.darken(Colors.green.shade700),
          brideGroomNameColor: ColorConverter.darken(Colors.green.shade700),
          brandBackgroundColor: Colors.grey.shade200.withValues(alpha: .7),
          brandTextColor: Colors.grey.shade600,
        ),
      ),
      heightAdjustment: heightAdjustment,
      initialPage: initialPage,
      useWrapper: useWrapper,
      viewAsSinglePage: viewAsSinglePage,
      noAnimate: noAnimate,
      viewType: viewType,
      invitationId: invitationId,
      invitationData: invitationData,
      imagesRaw: imagesRaw,
      brandProfile: brandProfile,
    );
  }
}
