import 'package:flutter/material.dart';
import 'package:iv_project_invitation_theme/iv_project_invitation_theme.dart';
import 'package:iv_project_invitation_theme/src/page_types/page_view_with_bottom_tab_bar.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/page_view_based.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_cover_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_eighth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_fifth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_first_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_fourth_different_location_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_fourth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_second_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_seventh_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_sixth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_third_different_location_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_third_page.dart';
import 'package:iv_project_invitation_theme/src/widgets/bubble_background.dart';
import 'package:iv_project_invitation_theme/src/widgets/particle_sphere.dart';
import 'package:iv_project_model/iv_project_model.dart';
import 'package:quick_dev_sdk/quick_dev_sdk.dart';

class ElegantBlackAndWhiteGlass extends StatelessWidget {
  const ElegantBlackAndWhiteGlass({
    super.key,
    this.heightAdjustment = 0,
    this.initialPage = 0,
    this.viewAsImage = false,
    required this.viewType,
    required this.invitationId,
    required this.invitationData,
    this.imagesRaw,
    required this.brandProfile,
  });

  final double heightAdjustment;
  final int initialPage;
  final bool viewAsImage;
  final ViewType viewType;
  final String invitationId;
  final InvitationDataResponse invitationData;
  final ImagesRaw? imagesRaw;
  final BrandProfileResponse brandProfile;

  @override
  Widget build(BuildContext context) {
    return PageViewBased(
      configs: PageViewBasedConfigs(
        tabConfig: TabConfig(
          useGlassEffect: true,
          indicatorColor: Colors.grey.shade50,
          backgroundColor: Colors.black.withValues(alpha: .5),
          titleActiveColor: Colors.white,
          titleInactiveColor: Colors.grey.shade400,
          iconActiveColor: Colors.white,
          iconInactiveColor: Colors.grey.shade400,
        ),
        globalBackgroundsBuilder: () => [
          BubbleBackground(
            backgroundColor: Colors.grey.shade300,
            bubbleColor1: Colors.grey.shade900,
            bubbleColor2: Colors.grey.shade600,
            bubbleColor3: Colors.grey.shade600,
            bubbleColor4: Colors.grey.shade500,
            bubbleColor5: Colors.grey.shade400,
          ),
        ],
        particleSphere: ParticleSphereConfig(
          particleVariatios: [
            Particle.circle(color: Colors.grey),
            Particle.circle(color: Colors.white),
            Particle.circle(color: ColorConverter.darken(Colors.grey.shade700, 40)),
          ],
        ),
        coverPageConfig: PageViewBasedCoverPageConfig(
          gradientBaseColor: Colors.grey.shade900,
          brideNameColor: Colors.grey.shade300,
          groomNameColor: Colors.grey.shade300,
          countdownBorderWidth: 1,
          countdownOddColor: Colors.grey.shade500.withValues(alpha: .1),
          countdownEvenColor: Colors.grey.shade500.withValues(alpha: .1),
          countdownOddBorderColor: Colors.grey.shade600,
          countdownEvenBorderColor: Colors.grey.shade600,
          countdownNumberColor: Colors.grey.shade200,
          countdownUnitColor: Colors.grey.shade200,
          useLightningEffectOnCountdown: true,
          firstArrowColor: Colors.grey.shade100.withValues(alpha: .7),
          secondArrowColor: Colors.grey.shade300.withValues(alpha: .5),
        ),
        firstPageConfig: PageViewBasedFirstPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: Colors.grey.shade900,
          secondGradientBackgroundColor: Colors.transparent,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade200,
          openingTextColor: Colors.grey.shade100,
          generalTextColor: Colors.grey.shade100,
          firstSubScaffoldColor: Colors.white.withValues(alpha: .05),
          firstSubScaffoldBorderColor: Colors.grey.shade500,
          firstSubScaffoldBorderWidth: .5,
          secondSubScaffoldColor: Colors.white.withValues(alpha: .05),
          secondSubScaffoldBorderColor: Colors.grey.shade500,
          secondSubScaffoldBorderWidth: .5,
        ),
        secondPageConfig: PageViewBasedSecondPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade900,
          generalTextColor: Colors.grey.shade200,
          brideDividingBorderWidth: .5,
          brideImageBorderWidth: .5,
          brideDividingLineWidth: .5,
          brideDividingBorderColor: Colors.grey.shade200,
          brideImageFrameColor: Colors.grey.shade200.withValues(alpha: .3),
          brideImageFrameBorderColor: Colors.grey.shade200,
          brideDividingLineColor: Colors.grey.shade200,
          brideNameTextColor: null,
          brideFatherNameTextColor: null,
          brideMotherNameTextColor: null,
          groomDividingBorderWidth: .5,
          groomImageBorderWidth: .5,
          groomDividingLineWidth: .5,
          groomDividingBorderColor: Colors.grey.shade200,
          groomImageFrameColor: Colors.grey.shade200.withValues(alpha: .3),
          groomImageFrameBorderColor: Colors.grey.shade200,
          groomDividingLineColor: Colors.grey.shade200,
          groomNameTextColor: null,
          groomFatherNameTextColor: null,
          groomMotherNameTextColor: null,
        ),
        thirdPageConfig: PageViewBasedThirdPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: Colors.transparent,
          secondGradientBackgroundColor: Colors.grey.shade900,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade900,
          contractTitleColor: Colors.grey.shade100,
          contractBaseTextColor: Colors.grey.shade100,
          receptionTitleColor: Colors.grey.shade100,
          receptionBaseTextColor: Colors.grey.shade100,
          dividingLineWidth: .5,
          dividingLineColor: Colors.grey.shade100,
          contractCountdownBorderWidth: 1,
          contractCountdownOddColor: Colors.grey.shade500.withValues(alpha: .1),
          contractCountdownEvenColor: Colors.grey.shade500.withValues(alpha: .1),
          contractCountdownOddBorderColor: Colors.grey.shade600,
          contractCountdownEvenBorderColor: Colors.grey.shade600,
          contractCountdownNumberColor: Colors.grey.shade200,
          contractCountdownUnitColor: Colors.grey.shade200,
          receptionCountdownBorderWidth: 1,
          receptionCountdownOddColor: Colors.grey.shade500.withValues(alpha: .1),
          receptionCountdownEvenColor: Colors.grey.shade500.withValues(alpha: .1),
          receptionCountdownOddBorderColor: Colors.grey.shade600,
          receptionCountdownEvenBorderColor: Colors.grey.shade600,
          receptionCountdownNumberColor: Colors.grey.shade200,
          receptionCountdownUnitColor: Colors.grey.shade200,
          useLightningEffectOnCountdown: true,
        ),
        thirdDifferentLocationPageConfig: PageViewBasedThirdDifferentLocationPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: Colors.transparent,
          secondGradientBackgroundColor: Colors.grey.shade900,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade900,
          dateTimeIconColor: Colors.grey.shade100,
          dateTimeBaseTextColor: Colors.grey.shade100,
          countdownBorderWidth: 1,
          countdownOddColor: Colors.grey.shade800.withValues(alpha: .1),
          countdownEvenColor: Colors.grey.shade800.withValues(alpha: .1),
          countdownOddBorderColor: Colors.grey.shade500,
          countdownEvenBorderColor: Colors.grey.shade500,
          countdownNumberColor: Colors.grey.shade200,
          countdownUnitColor: Colors.grey.shade200,
          useLightningEffectOnCountdown: false,
          dividingLineWidth: .5,
          dividingLineColor: Colors.grey.shade100,
          placeIconColor: Colors.grey.shade100,
          placeBaseTextColor: Colors.grey.shade100,
          addressTextColor: Colors.grey.shade100,
          mapsBorderColor: Colors.grey.shade400,
          getDirectionsButtonColor: Colors.grey.shade300.withValues(alpha: .2),
          getDirectionsButtonLabelColor: Colors.white,
          getDirectionsButtonBorderWidth: .5,
          getDirectionsButtonBorderColor: Colors.grey.shade500,
        ),
        fourthPageConfig: PageViewBasedFourthPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: Colors.grey.shade900,
          secondGradientBackgroundColor: Colors.transparent,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade200,
          placeIconColor: Colors.grey.shade50,
          placeTextColor: Colors.grey.shade50,
          addressTextColor: Colors.grey.shade50,
          dividingLineWidth: .5,
          dividingLineColor: Colors.grey.shade50,
          mapsBorderColor: Colors.grey.shade400,
          getDirectionsButtonColor: Colors.grey.shade300.withValues(alpha: .2),
          getDirectionsButtonLabelColor: Colors.white,
          getDirectionsButtonBorderWidth: .5,
          getDirectionsButtonBorderColor: Colors.grey.shade500,
        ),
        fourthDifferentLocationPageConfig: PageViewBasedFourthDifferentLocationPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: Colors.grey.shade900,
          secondGradientBackgroundColor: Colors.transparent,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade200,
          dateTimeIconColor: Colors.grey.shade50,
          dateTimeBaseTextColor: Colors.grey.shade50,
          countdownBorderWidth: 1,
          countdownOddColor: Colors.grey.shade500.withValues(alpha: .1),
          countdownEvenColor: Colors.grey.shade500.withValues(alpha: .1),
          countdownOddBorderColor: Colors.grey.shade600,
          countdownEvenBorderColor: Colors.grey.shade600,
          countdownNumberColor: Colors.grey.shade200,
          countdownUnitColor: Colors.grey.shade200,
          useLightningEffectOnCountdown: false,
          dividingLineWidth: .5,
          dividingLineColor: Colors.grey.shade50,
          placeIconColor: Colors.grey.shade50,
          placeBaseTextColor: Colors.grey.shade50,
          addressTextColor: Colors.grey.shade50,
          mapsBorderColor: Colors.grey.shade400,
          getDirectionsButtonColor: Colors.grey.shade300.withValues(alpha: .2),
          getDirectionsButtonLabelColor: Colors.white,
          getDirectionsButtonBorderWidth: .5,
          getDirectionsButtonBorderColor: Colors.grey.shade500,
        ),
        fifthPageConfig: PageViewBasedFifthPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade900,
          dividingLineWidth: .5,
          dividingVerticalLineColor: Colors.grey.shade500,
          dividingHorizontalLineColor: Colors.grey.shade500,
          seeMoreButtonColor: Colors.black.withValues(alpha: .5),
          seeMoreButtonLabelColor: Colors.grey.shade50,
          seeMoreButtonBorderWidth: .5,
          seeMoreButtonBorderColor: Colors.grey.shade500,
          bottomSheetHandleColor: null,
          bottomSheetContentScaffoldColor: Colors.grey.shade700.withValues(alpha: .5),
          bottomSheetBackgroundColor: Colors.black.withValues(alpha: .85),
          bottomSheetCloseIconColor: Colors.grey.shade400,
        ),
        sixthPageConfig: PageViewBasedSixthPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientBackgroundColor: Colors.transparent,
          secondGradientBackgroundColor: Colors.grey.shade900,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade900,
          introductionTextColor: Colors.grey.shade100,
          introductionColor: Colors.white.withValues(alpha: .05),
          introductionBorderColor: Colors.grey.shade500,
          introductionBorderWidth: .5,
          bankColor: Colors.white.withValues(alpha: .05),
          bankBorderColor: Colors.grey.shade500,
          bankBorderWidth: .5,
          bankTextColor: Colors.grey.shade100,
          bankCopyBaseColor: Colors.grey.shade400,
        ),
        seventhPageConfig: PageViewBasedSeventhPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade900,
          fieldTextColor: Colors.grey.shade100,
          fieldLabelColor: Colors.grey.shade300,
          fieldFillColor: Colors.grey.shade500.withValues(alpha: .3),
          fieldBorderColor: Colors.grey.shade600,
          fieldSplashColor: Colors.grey.shade400,
          overlayColor: Colors.grey.shade700.withValues(alpha: .95),
          overlayBorderColor: Colors.grey.shade500,
          dropdownItemSelectedColor: Colors.grey.shade500,
          dropdownItemTextColor: Colors.grey.shade100,
          dropdownItemSelectedTextColor: Colors.grey.shade100,
          dropdownItemHoveredColor: Colors.grey.shade400,
          dropdownItemSplashColor: Colors.grey.shade400,
          submitButtonColor: Colors.black.withValues(alpha: .3),
          submitButtonLabelColor: Colors.grey.shade100,
          submitButtonBorderWidth: .5,
          submitButtonBorderColor: Colors.grey.shade500,
          rsvpBackgroundColor: Colors.grey.shade500.withValues(alpha: .3),
          rsvpBorderColor: Colors.grey.shade500,
          rsvpNameTextColor: Colors.grey.shade100,
          rsvpTimeAgoTextColor: Colors.grey.shade400,
          rsvpNameInstanceTextColor: Colors.grey.shade400,
          rsvpAttendanceTextColorLighten: 50,
          rsvpMessageTextColor: Colors.grey.shade200,
          seeMoreButtonColor: Colors.grey.shade900.withValues(alpha: .8),
          seeMoreButtonLabelColor: Colors.grey.shade100,
          seeMoreButtonBorderWidth: .5,
          seeMoreButtonBorderColor: Colors.grey.shade500,
          bottomSheetHandleColor: null,
          bottomSheetContentScaffoldColor: Colors.grey.shade700.withValues(alpha: .5),
          bottomSheetBackgroundColor: Colors.black.withValues(alpha: .85),
          bottomSheetCloseIconColor: Colors.grey.shade400,
        ),
        eighthPageConfig: PageViewBasedEighthPageConfig(
          useBackdropBlurOnScaffold: true,
          firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
          scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
          useGlassEffectOnScaffold: true,
          titlePageColor: Colors.grey.shade900,
          closingTextColor: Colors.grey.shade100,
          brideGroomNameColor: Colors.grey.shade100,
          brandBackgroundColor: Colors.grey.shade200.withValues(alpha: .7),
          brandTextColor: Colors.grey.shade600,
        ),
      ),
      heightAdjustment: heightAdjustment,
      initialPage: initialPage,
      viewAsImage: viewAsImage,
      viewType: viewType,
      invitationId: invitationId,
      invitationData: invitationData,
      imagesRaw: imagesRaw,
      brandProfile: brandProfile,
    );
  }
}
