class H {
  const H._();

  static late double x16s;
  static late double x15s;
  static late double x14s;
  static late double x13s;
  static late double x12s;
  static late double x11s;
  static late double x10s;
  static late double x9s;
  static late double x8s;
  static late double x7s;
  static late double x6s;
  static late double x5s;
  static late double x4s;
  static late double x3s;
  static late double x2s;
  static late double xs;
  static late double sm;
  static late double md;
  static late double lg;
  static late double xl;
  static late double x2l;
  static late double x3l;
  static late double x4l;
  static late double x5l;
  static late double x6l;
  static late double x7l;
  static late double x8l;
  static late double x9l;
  static late double x10l;
  static late double x11l;
  static late double x12l;
  static late double x13l;
  static late double x14l;
  static late double x15l;
  static late double x16l;
  static late double x17l;
  static late double x18l;
  static late double x19l;
  static late double x20l;
  static late double x21l;
  static late double x22l;

  static void set(double height) {
    final heightFactor = height / 812;
    x16s = 1 * heightFactor;
    x15s = 2 * heightFactor;
    x14s = 3 * heightFactor;
    x13s = 4 * heightFactor;
    x12s = 5 * heightFactor;
    x11s = 6 * heightFactor;
    x10s = 7 * heightFactor;
    x9s = 8 * heightFactor;
    x8s = 10 * heightFactor;
    x7s = 12 * heightFactor;
    x6s = 14 * heightFactor;
    x5s = 16 * heightFactor;
    x4s = 18 * heightFactor;
    x3s = 20 * heightFactor;
    x2s = 24 * heightFactor;
    xs = 28 * heightFactor;
    sm = 32 * heightFactor;
    md = 36 * heightFactor;
    lg = 40 * heightFactor;
    xl = 44 * heightFactor;
    x2l = 48 * heightFactor;
    x3l = 52 * heightFactor;
    x4l = 56 * heightFactor;
    x5l = 64 * heightFactor;
    x6l = 72 * heightFactor;
    x7l = 80 * heightFactor;
    x8l = 88 * heightFactor;
    x9l = 96 * heightFactor;
    x10l = 112 * heightFactor;
    x11l = 128 * heightFactor;
    x12l = 144 * heightFactor;
    x13l = 160 * heightFactor;
    x14l = 176 * heightFactor;
    x15l = 192 * heightFactor;
    x16l = 224 * heightFactor;
    x17l = 256 * heightFactor;
    x18l = 288 * heightFactor;
    x19l = 320 * heightFactor;
    x20l = 384 * heightFactor;
    x21l = 448 * heightFactor;
    x22l = 512 * heightFactor;
  }
}
