import 'package:flutter/material.dart';

class SizeScale {
  const SizeScale._();

  static late double heightX9s;
  static late double heightX8s;
  static late double heightX7s;
  static late double heightX6s;
  static late double heightX5s;
  static late double heightX4s;
  static late double heightX3s;
  static late double heightX2s;
  static late double heightXs;
  static late double heightSm;
  static late double heightMd;
  static late double heightLg;
  static late double heightXl;
  static late double heightX2l;
  static late double heightX3l;
  static late double heightX4l;
  static late double heightX5l;
  static late double heightX6l;
  static late double heightX7l;
  static late double heightX8l;
  static late double heightX9l;
  static late double heightX10l;
  static late double heightX11l;
  static late double heightX12l;
  static late double heightX13l;
  static late double heightX14l;
  static late double heightX15l;
  static late double heightX16l;
  static late double heightX17l;
  static late double heightX18l;
  static late double heightX19l;
  static late double heightX20l;
  static late double heightX21l;
  static late double heightX22l;

  static late double widthX9s;
  static late double widthX8s;
  static late double widthX7s;
  static late double widthX6s;
  static late double widthX5s;
  static late double widthX4s;
  static late double widthX3s;
  static late double widthX2s;
  static late double widthXs;
  static late double widthSm;
  static late double widthMd;
  static late double widthLg;
  static late double widthXl;
  static late double widthX2l;
  static late double widthX3l;
  static late double widthX4l;
  static late double widthX5l;
  static late double widthX6l;
  static late double widthX7l;
  static late double widthX8l;
  static late double widthX9l;
  static late double widthX10l;
  static late double widthX11l;
  static late double widthX12l;
  static late double widthX13l;
  static late double widthX14l;
  static late double widthX15l;
  static late double widthX16l;
  static late double widthX17l;
  static late double widthX18l;
  static late double widthX19l;
  static late double widthX20l;
  static late double widthX21l;
  static late double widthX22l;

  static void set(Size screenSize) {
    final heightFactor = screenSize.height / 812;
    heightX9s = 8 * heightFactor;
    heightX8s = 10 * heightFactor;
    heightX7s = 12 * heightFactor;
    heightX6s = 14 * heightFactor;
    heightX5s = 16 * heightFactor;
    heightX4s = 18 * heightFactor;
    heightX3s = 20 * heightFactor;
    heightX2s = 24 * heightFactor;
    heightXs = 28 * heightFactor;
    heightSm = 32 * heightFactor;
    heightMd = 36 * heightFactor;
    heightLg = 40 * heightFactor;
    heightXl = 44 * heightFactor;
    heightX2l = 48 * heightFactor;
    heightX3l = 52 * heightFactor;
    heightX4l = 56 * heightFactor;
    heightX5l = 64 * heightFactor;
    heightX6l = 72 * heightFactor;
    heightX7l = 80 * heightFactor;
    heightX8l = 88 * heightFactor;
    heightX9l = 96 * heightFactor;
    heightX10l = 112 * heightFactor;
    heightX11l = 128 * heightFactor;
    heightX12l = 144 * heightFactor;
    heightX13l = 160 * heightFactor;
    heightX14l = 176 * heightFactor;
    heightX15l = 192 * heightFactor;
    heightX16l = 224 * heightFactor;
    heightX17l = 256 * heightFactor;
    heightX18l = 288 * heightFactor;
    heightX19l = 320 * heightFactor;
    heightX20l = 384 * heightFactor;
    heightX21l = 448 * heightFactor;
    heightX22l = 512 * heightFactor;

    final widthFactor = screenSize.width / 375;
    widthX9s = 8 * widthFactor;
    widthX8s = 10 * widthFactor;
    widthX7s = 12 * widthFactor;
    widthX6s = 14 * widthFactor;
    widthX5s = 16 * widthFactor;
    widthX4s = 18 * widthFactor;
    widthX3s = 20 * widthFactor;
    widthX2s = 24 * widthFactor;
    widthXs = 28 * widthFactor;
    widthSm = 32 * widthFactor;
    widthMd = 36 * widthFactor;
    widthLg = 40 * widthFactor;
    widthXl = 44 * widthFactor;
    widthX2l = 48 * widthFactor;
    widthX3l = 52 * widthFactor;
    widthX4l = 56 * widthFactor;
    widthX5l = 64 * widthFactor;
    widthX6l = 72 * widthFactor;
    widthX7l = 80 * widthFactor;
    widthX8l = 88 * widthFactor;
    widthX9l = 96 * widthFactor;
    widthX10l = 112 * widthFactor;
    widthX11l = 128 * widthFactor;
    widthX12l = 144 * widthFactor;
    widthX13l = 160 * widthFactor;
    widthX14l = 176 * widthFactor;
    widthX15l = 192 * widthFactor;
    widthX16l = 224 * widthFactor;
    widthX17l = 256 * widthFactor;
    widthX18l = 288 * widthFactor;
    widthX19l = 320 * widthFactor;
    widthX20l = 384 * widthFactor;
    widthX21l = 448 * widthFactor;
    widthX22l = 512 * widthFactor;
  }
}
