class W {
  const W._();

  static late double x16s;
  static late double x15s;
  static late double x14s;
  static late double x13s;
  static late double x12s;
  static late double x11s;
  static late double x10s;
  static late double x9s;
  static late double x8s;
  static late double x7s;
  static late double x6s;
  static late double x5s;
  static late double x4s;
  static late double x3s;
  static late double x2s;
  static late double xs;
  static late double sm;
  static late double md;
  static late double lg;
  static late double xl;
  static late double x2l;
  static late double x3l;
  static late double x4l;
  static late double x5l;
  static late double x6l;
  static late double x7l;
  static late double x8l;
  static late double x9l;
  static late double x10l;
  static late double x11l;
  static late double x12l;
  static late double x13l;
  static late double x14l;
  static late double x15l;
  static late double x16l;
  static late double x17l;
  static late double x18l;
  static late double x19l;
  static late double x20l;
  static late double x21l;
  static late double x22l;

  static void set(double width) {
    final widthFactor = width / 375;
    x16s = 1 * widthFactor;
    x15s = 2 * widthFactor;
    x14s = 3 * widthFactor;
    x13s = 4 * widthFactor;
    x12s = 5 * widthFactor;
    x11s = 6 * widthFactor;
    x10s = 7 * widthFactor;
    x9s = 8 * widthFactor;
    x8s = 10 * widthFactor;
    x7s = 12 * widthFactor;
    x6s = 14 * widthFactor;
    x5s = 16 * widthFactor;
    x4s = 18 * widthFactor;
    x3s = 20 * widthFactor;
    x2s = 24 * widthFactor;
    xs = 28 * widthFactor;
    sm = 32 * widthFactor;
    md = 36 * widthFactor;
    lg = 40 * widthFactor;
    xl = 44 * widthFactor;
    x2l = 48 * widthFactor;
    x3l = 52 * widthFactor;
    x4l = 56 * widthFactor;
    x5l = 64 * widthFactor;
    x6l = 72 * widthFactor;
    x7l = 80 * widthFactor;
    x8l = 88 * widthFactor;
    x9l = 96 * widthFactor;
    x10l = 112 * widthFactor;
    x11l = 128 * widthFactor;
    x12l = 144 * widthFactor;
    x13l = 160 * widthFactor;
    x14l = 176 * widthFactor;
    x15l = 192 * widthFactor;
    x16l = 224 * widthFactor;
    x17l = 256 * widthFactor;
    x18l = 288 * widthFactor;
    x19l = 320 * widthFactor;
    x20l = 384 * widthFactor;
    x21l = 448 * widthFactor;
    x22l = 512 * widthFactor;
  }
}
