import 'package:flutter/material.dart';
import 'package:iv_project_core/iv_project_core.dart';
import 'package:iv_project_invitation_theme/src/theme_family/gemini_star_theme/gemini_star_configs.dart';
import 'package:iv_project_invitation_theme/src/widgets/gemini_star_frame.dart';
import 'package:quick_dev_sdk/quick_dev_sdk.dart';

class BlackAndWhiteGeminiStar {
  BlackAndWhiteGeminiStar._();

  static GeminiStarConfigs get configs => GeminiStarConfigs(
    globalBackgroundsBuilder: () => [SizedBox(height: Screen.height, width: Screen.width)],
    coverPageConfig: GeminiStarCoverPageConfig(
      gradientBaseColor: Colors.grey.shade900,
      brideNameColor: Colors.grey.shade300,
      groomNameColor: Colors.grey.shade300,
      countdownBorderWidth: 1,
      countdownOddColor: Colors.grey.shade600.withValues(alpha: .4),
      countdownEvenColor: Colors.grey.shade600.withValues(alpha: .4),
      countdownOddBorderColor: Colors.grey.shade600,
      countdownEvenBorderColor: Colors.grey.shade600,
      countdownNumberColor: Colors.grey.shade200,
      countdownUnitColor: Colors.grey.shade200,
      firstArrowColor: Colors.grey.shade100.withValues(alpha: .7),
      secondArrowColor: Colors.grey.shade300.withValues(alpha: .5),
    ),
    firstPageConfig: GeminiStarFirstPageConfig(
      decorationBuilder: () => GeminiStarFrame(
        color: ColorUtil.lighten(Colors.grey.shade600, 25),
        lineWidth: 2,
        starRadius: 20,
        showStars: const ShowStars(topRight: false, bottomLeft: false),
        starOffsets: StarOffsets(left: W.sm, top: 60, right: W.sm, bottom: W.sm),
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .1),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade400,
      openingTextColor: Colors.grey.shade300,
      generalTextColor: Colors.grey.shade300,
      firstSubScaffoldColor: Colors.white.withValues(alpha: .05),
      firstSubScaffoldBorderColor: Colors.grey.shade500,
      firstSubScaffoldBorderWidth: .5,
      secondSubScaffoldColor: Colors.white.withValues(alpha: .05),
      secondSubScaffoldBorderColor: Colors.grey.shade500,
      secondSubScaffoldBorderWidth: .5,
    ),
    secondPageConfig: GeminiStarSecondPageConfig(
      decorationBuilder: () => Column(
        children: [
          Expanded(
            child: SizedBox(
              width: .infinity,
              child: GeminiStarFrame(
                color: Colors.grey.shade900,
                lineWidth: 2,
                starRadius: 20,
                showStars: const ShowStars(topRight: false),
                starOffsets: StarOffsets(left: W.sm, top: 60, right: W.sm),
              ),
            ),
          ),
          SizedBox(height: H.x16l + W.sm, width: .infinity),
        ],
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .0),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade900,
      generalTextColor: Colors.grey.shade300,
      brideDividingBorderWidth: .5,
      brideImageBorderWidth: .5,
      brideDividingLineWidth: .5,
      brideDividingBorderColor: Colors.grey.shade200,
      brideImageFrameColor: Colors.grey.shade200.withValues(alpha: .1),
      brideImageFrameBorderColor: Colors.grey.shade200,
      brideDividingLineColor: Colors.grey.shade200,
      brideNameTextColor: null,
      brideFatherNameTextColor: null,
      brideMotherNameTextColor: null,
      groomDividingBorderWidth: .5,
      groomImageBorderWidth: .5,
      groomDividingLineWidth: .5,
      groomDividingBorderColor: Colors.grey.shade200,
      groomImageFrameColor: Colors.grey.shade200.withValues(alpha: .1),
      groomImageFrameBorderColor: Colors.grey.shade200,
      groomDividingLineColor: Colors.grey.shade200,
      groomNameTextColor: null,
      groomFatherNameTextColor: null,
      groomMotherNameTextColor: null,
    ),
    thirdPageConfig: GeminiStarThirdPageConfig(
      decorationBuilder: () => Column(
        children: [
          Expanded(
            child: SizedBox(
              width: .infinity,
              child: GeminiStarFrame(
                color: Colors.grey.shade900,
                lineWidth: 2,
                starRadius: 20,
                showStars: const ShowStars(topRight: false),
                starOffsets: StarOffsets(left: W.sm, top: 60, right: W.sm),
              ),
            ),
          ),
          SizedBox(height: H.x16l + W.sm, width: .infinity),
        ],
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .0),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade900,
      generalTextColor: Colors.grey.shade300,
      brideDividingBorderWidth: .5,
      brideImageBorderWidth: .5,
      brideDividingLineWidth: .5,
      brideDividingBorderColor: Colors.grey.shade200,
      brideImageFrameColor: Colors.grey.shade200.withValues(alpha: .1),
      brideImageFrameBorderColor: Colors.grey.shade200,
      brideDividingLineColor: Colors.grey.shade200,
      brideNameTextColor: null,
      brideFatherNameTextColor: null,
      brideMotherNameTextColor: null,
      groomDividingBorderWidth: .5,
      groomImageBorderWidth: .5,
      groomDividingLineWidth: .5,
      groomDividingBorderColor: Colors.grey.shade200,
      groomImageFrameColor: Colors.grey.shade200.withValues(alpha: .1),
      groomImageFrameBorderColor: Colors.grey.shade200,
      groomDividingLineColor: Colors.grey.shade200,
      groomNameTextColor: null,
      groomFatherNameTextColor: null,
      groomMotherNameTextColor: null,
    ),
    fourthPageConfig: GeminiStarFourthPageConfig(
      decorationBuilder: () => GeminiStarFrame(
        color: Colors.grey.shade600,
        lineWidth: 2,
        starRadius: 20,
        showStars: const ShowStars(bottomLeft: false, bottomRight: false),
        starOffsets: StarOffsets(left: W.sm, top: Screen.height / 2, right: W.sm, bottom: W.sm),
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .3),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade400,
      contractTitleColor: Colors.grey.shade100,
      contractBaseTextColor: Colors.grey.shade100,
      receptionTitleColor: Colors.grey.shade100,
      receptionBaseTextColor: Colors.grey.shade100,
      dividingLineWidth: .5,
      dividingLineColor: Colors.grey.shade100,
      contractCountdownBorderWidth: 1,
      contractCountdownOddColor: Colors.grey.shade700.withValues(alpha: .75),
      contractCountdownEvenColor: Colors.grey.shade700.withValues(alpha: .75),
      contractCountdownOddBorderColor: Colors.grey.shade500,
      contractCountdownEvenBorderColor: Colors.grey.shade500,
      contractCountdownNumberColor: Colors.grey.shade200,
      contractCountdownUnitColor: Colors.grey.shade200,
      receptionCountdownBorderWidth: 1,
      receptionCountdownOddColor: Colors.grey.shade700.withValues(alpha: .75),
      receptionCountdownEvenColor: Colors.grey.shade700.withValues(alpha: .75),
      receptionCountdownOddBorderColor: Colors.grey.shade500,
      receptionCountdownEvenBorderColor: Colors.grey.shade500,
      receptionCountdownNumberColor: Colors.grey.shade200,
      receptionCountdownUnitColor: Colors.grey.shade200,
    ),
    fourthDifferentLocationPageConfig: GeminiStarFourthDifferentLocationPageConfig(
      decorationBuilder: () => GeminiStarFrame(
        color: Colors.grey.shade500,
        lineWidth: 2,
        starRadius: 20,
        showStars: const ShowStars(),
        starOffsets: StarOffsets(
          top: H.x20l + H.md,
          bottom: H.x12l - H.x3s,
          left: W.sm,
          right: W.sm,
        ),
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .25),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade400,
      dateTimeIconColor: Colors.grey.shade100,
      dateTimeBaseTextColor: Colors.grey.shade100,
      countdownBorderWidth: 1,
      countdownOddColor: Colors.grey.shade700.withValues(alpha: .5),
      countdownEvenColor: Colors.grey.shade700.withValues(alpha: .5),
      countdownOddBorderColor: Colors.grey.shade400,
      countdownEvenBorderColor: Colors.grey.shade400,
      countdownNumberColor: Colors.grey.shade100,
      countdownUnitColor: Colors.grey.shade100,
      dividingLineWidth: .5,
      dividingLineColor: Colors.grey.shade100,
      placeIconColor: Colors.grey.shade100,
      placeBaseTextColor: Colors.grey.shade100,
      addressTextColor: Colors.grey.shade100,
      mapsBorderColor: Colors.grey.shade400,
      getDirectionsButtonColor: Colors.black.withValues(alpha: .5),
      getDirectionsButtonLabelColor: Colors.white,
      getDirectionsButtonBorderWidth: .5,
      getDirectionsButtonBorderColor: Colors.grey.shade500,
    ),
    fifthPageConfig: GeminiStarFifthPageConfig(
      decorationBuilder: () => GeminiStarFrame(
        color: Colors.grey.shade500,
        lineWidth: 2,
        starRadius: 20,
        showStars: const ShowStars(),
        starOffsets: StarOffsets(top: H.x17l, bottom: H.x15l, left: W.sm, right: W.sm),
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .5),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade400,
      placeIconColor: Colors.grey.shade50,
      placeTextColor: Colors.grey.shade50,
      addressTextColor: Colors.grey.shade50,
      dividingLineWidth: .5,
      dividingLineColor: Colors.grey.shade50,
      mapsBorderColor: Colors.grey.shade400,
      getDirectionsButtonColor: Colors.black.withValues(alpha: .5),
      getDirectionsButtonLabelColor: Colors.white,
      getDirectionsButtonBorderWidth: .5,
      getDirectionsButtonBorderColor: Colors.grey.shade500,
    ),
    fifthDifferentLocationPageConfig: GeminiStarFifthDifferentLocationPageConfig(
      decorationBuilder: () => GeminiStarFrame(
        color: Colors.grey.shade500,
        lineWidth: 2,
        starRadius: 20,
        showStars: const ShowStars(),
        starOffsets: StarOffsets(
          top: H.x20l + H.md,
          bottom: H.x12l - H.x3s,
          left: W.sm,
          right: W.sm,
        ),
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .25),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade400,
      dateTimeIconColor: Colors.grey.shade100,
      dateTimeBaseTextColor: Colors.grey.shade100,
      countdownBorderWidth: 1,
      countdownOddColor: Colors.grey.shade700.withValues(alpha: .5),
      countdownEvenColor: Colors.grey.shade700.withValues(alpha: .5),
      countdownOddBorderColor: Colors.grey.shade400,
      countdownEvenBorderColor: Colors.grey.shade400,
      countdownNumberColor: Colors.grey.shade100,
      countdownUnitColor: Colors.grey.shade100,
      dividingLineWidth: .5,
      dividingLineColor: Colors.grey.shade100,
      placeIconColor: Colors.grey.shade100,
      placeBaseTextColor: Colors.grey.shade100,
      addressTextColor: Colors.grey.shade100,
      mapsBorderColor: Colors.grey.shade400,
      getDirectionsButtonColor: Colors.black.withValues(alpha: .5),
      getDirectionsButtonLabelColor: Colors.white,
      getDirectionsButtonBorderWidth: .5,
      getDirectionsButtonBorderColor: Colors.grey.shade500,
    ),
    sixthPageConfig: GeminiStarSixthPageConfig(
      decorationBuilder: () => GeminiStarFrame(
        color: Colors.grey.shade500,
        lineWidth: 2,
        starRadius: 20,
        showStars: const ShowStars(topRight: false, bottomRight: false),
        starOffsets: StarOffsets(top: H.x17l, bottom: H.x15l, left: W.sm),
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .5),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade300,
      dividingLineWidth: .5,
      dividingVerticalLineColor: Colors.grey.shade500,
      dividingHorizontalLineColor: Colors.grey.shade500,
      seeMoreButtonColor: Colors.black.withValues(alpha: .5),
      seeMoreButtonLabelColor: Colors.grey.shade50,
      seeMoreButtonBorderWidth: .5,
      seeMoreButtonBorderColor: Colors.grey.shade500,
      bottomSheetHandleColor: null,
      bottomSheetContentScaffoldColor: Colors.grey.shade700.withValues(alpha: .5),
      bottomSheetBackgroundColor: Colors.black.withValues(alpha: .85),
      bottomSheetCloseIconColor: Colors.grey.shade400,
    ),
    seventhPageConfig: GeminiStarSeventhPageConfig(
      decorationBuilder: () => GeminiStarFrame(
        color: Colors.grey.shade600,
        lineWidth: 2,
        starRadius: 20,
        showStars: const ShowStars(bottomLeft: false, bottomRight: false),
        starOffsets: StarOffsets(top: (Screen.height / 2) - H.x6l, left: W.sm, right: W.sm),
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .5),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade500,
      introductionTextColor: Colors.grey.shade100,
      introductionColor: Colors.white.withValues(alpha: .05),
      introductionBorderColor: Colors.grey.shade500,
      introductionBorderWidth: .5,
      bankColor: Colors.white.withValues(alpha: .05),
      bankBorderColor: Colors.grey.shade500,
      bankBorderWidth: .5,
      bankTextColor: Colors.grey.shade100,
      bankCopyBaseColor: Colors.grey.shade400,
    ),
    eighthPageConfig: GeminiStarEighthPageConfig(
      decorationBuilder: () => GeminiStarFrame(
        color: Colors.grey.shade600,
        lineWidth: 2,
        starRadius: 20,
        showStars: const ShowStars(bottomLeft: false, bottomRight: false),
        starOffsets: StarOffsets(top: (Screen.height / 2), left: W.sm, right: W.sm),
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .85),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade500,
      fieldTextColor: Colors.grey.shade100,
      fieldLabelColor: Colors.grey.shade300,
      fieldFillColor: Colors.grey.shade500.withValues(alpha: .3),
      fieldBorderColor: Colors.grey.shade500.withValues(alpha: .6),
      fieldSplashColor: Colors.grey.shade400,
      overlayColor: Colors.grey.shade700.withValues(alpha: .95),
      overlayBorderColor: Colors.grey.shade500,
      dropdownItemSelectedColor: Colors.grey.shade500,
      dropdownItemTextColor: Colors.grey.shade100,
      dropdownItemSelectedTextColor: Colors.grey.shade100,
      // dropdownItemHoveredColor: Colors.grey.shade400,
      // dropdownItemSplashColor: Colors.grey.shade400,
      submitButtonColor: Colors.black.withValues(alpha: .3),
      submitButtonLabelColor: Colors.grey.shade100,
      submitButtonBorderWidth: .5,
      submitButtonBorderColor: Colors.grey.shade500,
      rsvpBackgroundColor: Colors.grey.shade500.withValues(alpha: .3),
      rsvpBorderColor: Colors.grey.shade500,
      rsvpNameTextColor: Colors.grey.shade100,
      rsvpTimeAgoTextColor: Colors.grey.shade400,
      rsvpNameInstanceTextColor: Colors.grey.shade400,
      rsvpAttendanceTextColorLighten: 50,
      rsvpMessageTextColor: Colors.grey.shade200,
      seeMoreButtonColor: Colors.grey.shade900.withValues(alpha: .8),
      seeMoreButtonLabelColor: Colors.grey.shade100,
      seeMoreButtonBorderWidth: .5,
      seeMoreButtonBorderColor: Colors.grey.shade500,
      bottomSheetHandleColor: null,
      bottomSheetContentScaffoldColor: Colors.grey.shade700.withValues(alpha: .5),
      bottomSheetBackgroundColor: Colors.black.withValues(alpha: .85),
      bottomSheetCloseIconColor: Colors.grey.shade400,
    ),
    ninthPageConfig: GeminiStarNinthPageConfig(
      decorationBuilder: () => Column(
        children: [
          Expanded(
            child: SizedBox(
              width: .infinity,
              child: GeminiStarFrame(
                color: Colors.grey.shade400,
                lineWidth: 2,
                starRadius: 20,
                showStars: const ShowStars(),
                starOffsets: StarOffsets(left: W.sm, top: 60, right: W.sm),
              ),
            ),
          ),
          SizedBox(height: H.x18l - H.x4s, width: .infinity),
        ],
      ),
      firstGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .5),
      secondGradientBackgroundColor: Colors.grey.shade900.withValues(alpha: .75),
      firstGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      secondGradientScaffoldColor: Colors.black.withValues(alpha: .6),
      scaffoldBorder: .all(width: .5, color: Colors.grey.shade500),
      titlePageColor: Colors.grey.shade200,
      closingTextColor: Colors.grey.shade100,
      brideGroomNameColor: Colors.grey.shade100,
      brandBackgroundColor: Colors.grey.shade400,
      brandTextColor: Colors.grey.shade600,
    ),
  );

  static ThemeData? get themeData => null;
}
