import 'package:flutter/material.dart';
import 'package:gradient_borders/box_borders/gradient_box_border.dart';
import 'package:iv_project_invitation_theme/iv_project_invitation_theme.dart';
import 'package:iv_project_invitation_theme/src/page_types/page_view_with_bottom_tab_bar.dart';
import 'package:iv_project_invitation_theme/src/themes/canvas/canvas_theme_global_background.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/page_view_based.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_cover_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_eighth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_fifth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_first_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_fourth_different_location_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_fourth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_second_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_seventh_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_sixth_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_third_different_location_page.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/pages/page_view_based_third_page.dart';
import 'package:iv_project_invitation_theme/src/widgets/particle_sphere.dart';
import 'package:iv_project_model/iv_project_model.dart';
import 'package:quick_dev_sdk/quick_dev_sdk.dart';

class CanvasTheme extends StatelessWidget {
  const CanvasTheme({
    super.key,
    this.heightAdjustment = 0,
    this.initialPage = 0,
    this.viewAsImage = false,
    required this.viewType,
    required this.invitationId,
    required this.invitationData,
    this.imagesRaw,
    required this.brandProfile,
  });

  final double heightAdjustment;
  final int initialPage;
  final bool viewAsImage;
  final ViewType viewType;
  final String invitationId;
  final InvitationDataResponse invitationData;
  final ImagesRaw? imagesRaw;
  final BrandProfileResponse brandProfile;

  @override
  Widget build(BuildContext context) {
    return Theme(
      data: ThemeData(
        inputDecorationTheme: InputDecorationTheme(
          floatingLabelStyle: TextStyle(color: ColorConverter.darken(Colors.blue.shade400, 50)),
        ),
        textSelectionTheme: TextSelectionThemeData(
          cursorColor: ColorConverter.darken(Colors.blue.shade400, 50),
          selectionHandleColor: ColorConverter.darken(Colors.blue.shade400, 50),
        ),
      ),
      child: PageViewBased(
        configs: PageViewBasedConfigs(
          tabConfig: TabConfig(
            useGlassEffect: false,
            useBackdropBlur: false,
            widthFull: true,
            indicatorColor: ColorConverter.darken(Colors.blue.shade400, 50),
            backgroundColor: Colors.white.withValues(alpha: .0),
            titleActiveColor: ColorConverter.darken(Colors.blue.shade400, 50),
            titleInactiveColor: Colors.white,
            iconActiveColor: ColorConverter.darken(Colors.blue.shade400, 50),
            iconInactiveColor: Colors.white,
          ),
          globalBackgroundsBuilder: () => [const CanvasThemeGlobalBackground()],
          particleSphere: ParticleSphereConfig(
            particleCount: 22,
            particleVariatios: [
              Particle.image(imagePath: 'assets/backgrounds/floral_leaf.png'),
              Particle.image(imagePath: 'assets/backgrounds/floral_flower_pink.png'),
              Particle.image(imagePath: 'assets/backgrounds/floral_flower_blue.png'),
              Particle.image(imagePath: 'assets/backgrounds/floral_flower_pink.png'),
            ],
          ),
          coverPageConfig: PageViewBasedCoverPageConfig(
            gradientBaseColor: ColorConverter.darken(Colors.blue.shade700, 60),
            brideNameColor: ColorConverter.darken(Colors.blue.shade100, 10),
            groomNameColor: ColorConverter.darken(Colors.blue.shade100, 10),
            countdownBorderWidth: 2,
            countdownOddColor: ColorConverter.darken(Colors.blue.shade100, 10).withValues(alpha: .1),
            countdownEvenColor: ColorConverter.darken(Colors.blue.shade100, 10).withValues(alpha: .1),
            countdownOddBorderColor: ColorConverter.darken(Colors.blue.shade100, 10),
            countdownEvenBorderColor: ColorConverter.darken(Colors.blue.shade100, 10),
            countdownNumberColor: ColorConverter.darken(Colors.blue.shade50, 5),
            countdownUnitColor: ColorConverter.darken(Colors.blue.shade50, 5),
            useLightningEffectOnCountdown: false,
            firstArrowColor: ColorConverter.darken(Colors.blue.shade100, 5),
            secondArrowColor: ColorConverter.darken(Colors.blue.shade100, 25).withValues(alpha: .8),
          ),
          firstPageConfig: PageViewBasedFirstPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            openingTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            generalTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            firstSubScaffoldColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            firstSubScaffoldBorderColor: Colors.white,
            firstSubScaffoldBorderWidth: 2.5,
            secondSubScaffoldColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            secondSubScaffoldBorderColor: Colors.white,
            secondSubScaffoldBorderWidth: 2.5,
          ),
          secondPageConfig: PageViewBasedSecondPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            generalTextColor: ColorConverter.darken(Colors.blue.shade300, 40),
            brideDividingBorderWidth: 2,
            brideImageBorderWidth: 2,
            brideDividingLineWidth: 1,
            brideDividingBorderColor: ColorConverter.darken(Colors.blue.shade500, 40),
            brideImageFrameColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            brideImageFrameBorderColor: Colors.white,
            brideDividingLineColor: ColorConverter.darken(Colors.blue.shade500, 40),
            brideNameTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            brideFatherNameTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            brideMotherNameTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            groomDividingBorderWidth: 2,
            groomImageBorderWidth: 2,
            groomDividingLineWidth: 1,
            groomDividingBorderColor: ColorConverter.darken(Colors.blue.shade500, 40),
            groomImageFrameColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            groomImageFrameBorderColor: Colors.white,
            groomDividingLineColor: ColorConverter.darken(Colors.blue.shade500, 40),
            groomNameTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            groomFatherNameTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            groomMotherNameTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
          ),
          thirdPageConfig: PageViewBasedThirdPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            contractTitleColor: ColorConverter.darken(Colors.blue.shade500, 40),
            contractBaseTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            receptionTitleColor: ColorConverter.darken(Colors.blue.shade500, 40),
            receptionBaseTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            dividingLineWidth: 2,
            dividingLineColor: ColorConverter.darken(Colors.blue.shade500, 40),
            contractCountdownBorderWidth: 2.5,
            contractCountdownOddColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            contractCountdownEvenColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            contractCountdownOddBorderColor: Colors.white,
            contractCountdownEvenBorderColor: Colors.white,
            contractCountdownNumberColor: ColorConverter.darken(Colors.blue.shade500, 40),
            contractCountdownUnitColor: ColorConverter.darken(Colors.blue.shade500, 40),
            receptionCountdownBorderWidth: 2.5,
            receptionCountdownOddColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            receptionCountdownEvenColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            receptionCountdownOddBorderColor: Colors.white,
            receptionCountdownEvenBorderColor: Colors.white,
            receptionCountdownNumberColor: ColorConverter.darken(Colors.blue.shade500, 40),
            receptionCountdownUnitColor: ColorConverter.darken(Colors.blue.shade500, 40),
            useLightningEffectOnCountdown: false,
          ),
          thirdDifferentLocationPageConfig: PageViewBasedThirdDifferentLocationPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            dateTimeIconColor: ColorConverter.darken(Colors.blue.shade500, 40),
            dateTimeBaseTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            countdownBorderWidth: 2.5,
            countdownOddColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            countdownEvenColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            countdownOddBorderColor: Colors.white,
            countdownEvenBorderColor: Colors.white,
            countdownNumberColor: ColorConverter.darken(Colors.blue.shade500, 40),
            countdownUnitColor: ColorConverter.darken(Colors.blue.shade500, 40),
            useLightningEffectOnCountdown: false,
            dividingLineWidth: 2,
            dividingLineColor: ColorConverter.darken(Colors.blue.shade500, 40),
            placeIconColor: ColorConverter.darken(Colors.blue.shade500, 40),
            placeBaseTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            addressTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            mapsBorderColor: Colors.grey.shade400,
            getDirectionsButtonColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            getDirectionsButtonLabelColor: ColorConverter.darken(Colors.blue.shade500, 40),
            getDirectionsButtonBorderWidth: 2,
            getDirectionsButtonBorderColor: ColorConverter.darken(Colors.blue.shade500, 40),
          ),
          fourthPageConfig: PageViewBasedFourthPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            placeIconColor: ColorConverter.darken(Colors.blue.shade500, 40),
            placeTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            addressTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            dividingLineWidth: 2,
            dividingLineColor: ColorConverter.darken(Colors.blue.shade500, 40),
            mapsBorderColor: Colors.grey.shade400,
            getDirectionsButtonColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            getDirectionsButtonLabelColor: ColorConverter.darken(Colors.blue.shade500, 40),
            getDirectionsButtonBorderWidth: 2,
            getDirectionsButtonBorderColor: ColorConverter.darken(Colors.blue.shade500, 40),
          ),
          fourthDifferentLocationPageConfig: PageViewBasedFourthDifferentLocationPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            dateTimeIconColor: ColorConverter.darken(Colors.blue.shade500, 40),
            dateTimeBaseTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            countdownBorderWidth: 2.5,
            countdownOddColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            countdownEvenColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            countdownOddBorderColor: Colors.white,
            countdownEvenBorderColor: Colors.white,
            countdownNumberColor: ColorConverter.darken(Colors.blue.shade500, 40),
            countdownUnitColor: ColorConverter.darken(Colors.blue.shade500, 40),
            useLightningEffectOnCountdown: false,
            dividingLineWidth: 2,
            dividingLineColor: ColorConverter.darken(Colors.blue.shade500, 40),
            placeIconColor: ColorConverter.darken(Colors.blue.shade500, 40),
            placeBaseTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            addressTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            mapsBorderColor: Colors.grey.shade400,
            getDirectionsButtonColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            getDirectionsButtonLabelColor: ColorConverter.darken(Colors.blue.shade500, 40),
            getDirectionsButtonBorderWidth: 2,
            getDirectionsButtonBorderColor: ColorConverter.darken(Colors.blue.shade500, 40),
          ),
          fifthPageConfig: PageViewBasedFifthPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            dividingLineWidth: 1.5,
            dividingVerticalLineColor: ColorConverter.darken(Colors.blue.shade500, 40),
            dividingHorizontalLineColor: ColorConverter.darken(Colors.blue.shade500, 40),
            seeMoreButtonColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            seeMoreButtonLabelColor: ColorConverter.darken(Colors.blue.shade500, 40),
            seeMoreButtonBorderWidth: 2,
            seeMoreButtonBorderColor: ColorConverter.darken(Colors.blue.shade500, 40),
            bottomSheetHandleColor: Colors.grey.shade300,
            bottomSheetContentScaffoldColor: Colors.white.withValues(alpha: .75),
            bottomSheetBackgroundColor: ColorConverter.darken(Colors.blue.shade100, 40).withValues(alpha: .95),
            bottomSheetCloseIconColor: Colors.grey.shade300,
          ),
          sixthPageConfig: PageViewBasedSixthPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            introductionTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            introductionColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            introductionBorderColor: Colors.white,
            introductionBorderWidth: 2.5,
            bankColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            bankBorderColor: Colors.white,
            bankBorderWidth: 2.5,
            bankTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            bankCopyBaseColor: ColorConverter.darken(Colors.blue.shade500, 40),
          ),
          seventhPageConfig: PageViewBasedSeventhPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            fieldTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            fieldLabelColor: ColorConverter.darken(Colors.blue.shade500, 40),
            fieldFillColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            fieldBorderColor: ColorConverter.darken(Colors.blue.shade500, 40),
            fieldSplashColor: ColorConverter.darken(Colors.blue.shade50, 10),
            overlayColor: ColorConverter.darken(Colors.blue.shade50, 5).withValues(alpha: .95),
            overlayBorderColor: Colors.white,
            dropdownItemSelectedColor: ColorConverter.darken(Colors.blue.shade100, 5),
            dropdownItemTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            dropdownItemSelectedTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            dropdownItemHoveredColor: ColorConverter.darken(Colors.blue.shade50, 10).withValues(alpha: .95),
            dropdownItemSplashColor: ColorConverter.darken(Colors.blue.shade100, 5),
            submitButtonColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            submitButtonLabelColor: ColorConverter.darken(Colors.blue.shade500, 40),
            submitButtonBorderWidth: 2,
            submitButtonBorderColor: ColorConverter.darken(Colors.blue.shade500, 40),
            rsvpBackgroundColor: ColorConverter.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            rsvpBorderColor: Colors.white,
            rsvpBorderWidth: 2.5,
            rsvpNameTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            rsvpTimeAgoTextColor: ColorConverter.darken(Colors.blue.shade400, 30),
            rsvpNameInstanceTextColor: ColorConverter.darken(Colors.blue.shade700, 40),
            rsvpAttendanceTextColorLighten: 5,
            rsvpMessageTextColor: ColorConverter.darken(Colors.blue.shade300, 40),
            seeMoreButtonColor: ColorConverter.darken(Colors.blue.shade50, 8).withValues(alpha: .2),
            seeMoreButtonLabelColor: ColorConverter.darken(Colors.blue.shade500, 40),
            seeMoreButtonBorderWidth: 2,
            seeMoreButtonBorderColor: ColorConverter.darken(Colors.blue.shade500, 40),
            bottomSheetHandleColor: Colors.grey.shade300,
            bottomSheetContentScaffoldColor: Colors.white.withValues(alpha: .75),
            bottomSheetBackgroundColor: ColorConverter.darken(Colors.blue.shade100, 40).withValues(alpha: .95),
            bottomSheetCloseIconColor: Colors.grey.shade300,
          ),
          eighthPageConfig: PageViewBasedEighthPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [ColorConverter.darken(Colors.blue.shade100, 10), ColorConverter.darken(Colors.blue.shade300, 30)],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            closingTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
            brideGroomNameColor: ColorConverter.darken(Colors.blue.shade500, 40),
            brandBackgroundColor: ColorConverter.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            brandTextColor: ColorConverter.darken(Colors.blue.shade500, 40),
          ),
        ),
        heightAdjustment: heightAdjustment,
        initialPage: initialPage,
        viewAsImage: viewAsImage,
        viewType: viewType,
        invitationId: invitationId,
        invitationData: invitationData,
        imagesRaw: imagesRaw,
        brandProfile: brandProfile,
      ),
    );
  }
}
