import 'package:flutter/material.dart';
import 'package:gradient_borders/box_borders/gradient_box_border.dart';
import 'package:iv_project_invitation_theme/src/page_types/page_view_with_bottom_tab_bar_config.dart';
import 'package:iv_project_invitation_theme/src/themes/canvas/canvas_theme_global_background.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/page_view_based_as_image.dart';
import 'package:iv_project_invitation_theme/src/themes/page_view_based_theme/page_view_based_configs.dart';
import 'package:iv_project_model/iv_project_model.dart';
import 'package:quick_dev_sdk/quick_dev_sdk.dart';

class CanvasThemeAsSinglePage extends StatelessWidget {
  const CanvasThemeAsSinglePage({
    super.key,
    this.initialPage = 0,
    required this.useWrapper,
    required this.invitationData,
    required this.brandProfile,
  });

  final int initialPage;
  final bool useWrapper;
  final InvitationDataResponse invitationData;
  final BrandProfileResponse brandProfile;

  @override
  Widget build(BuildContext context) {
    return Theme(
      data: ThemeData(
        inputDecorationTheme: InputDecorationTheme(
          floatingLabelStyle: TextStyle(color: ColorUtil.darken(Colors.blue.shade400, 50)),
        ),
        textSelectionTheme: TextSelectionThemeData(
          cursorColor: ColorUtil.darken(Colors.blue.shade400, 50),
          selectionHandleColor: ColorUtil.darken(Colors.blue.shade400, 50),
        ),
      ),
      child: PageViewBasedAsImage(
        configs: PageViewBasedConfigs(
          tabConfig: PageViewWithBottomTabBarConfig(
            useGlassEffect: false,
            useBackdropBlur: false,
            widthFull: true,
            indicatorColor: ColorUtil.darken(Colors.blue.shade400, 50),
            backgroundColor: Colors.white.withValues(alpha: .0),
            titleActiveColor: ColorUtil.darken(Colors.blue.shade400, 50),
            titleInactiveColor: Colors.white,
            iconActiveColor: ColorUtil.darken(Colors.blue.shade400, 50),
            iconInactiveColor: Colors.white,
          ),
          globalBackgroundsBuilder: () => [const CanvasThemeGlobalBackground()],
          // particleSphere: ParticleSphereConfig(
          //   particleCount: 22,
          //   particleVariatios: [
          //     Particle.image(imagePath: 'assets/backgrounds/floral_leaf.png'),
          //     Particle.image(imagePath: 'assets/backgrounds/floral_flower_pink.png'),
          //     Particle.image(imagePath: 'assets/backgrounds/floral_flower_blue.png'),
          //   ],
          // ),
          coverPageConfig: PageViewBasedCoverPageConfig(
            gradientBaseColor: ColorUtil.darken(Colors.blue.shade700, 60),
            brideNameColor: ColorUtil.darken(Colors.blue.shade100, 10),
            groomNameColor: ColorUtil.darken(Colors.blue.shade100, 10),
            countdownBorderWidth: 2,
            countdownOddColor: ColorUtil.darken(Colors.blue.shade100, 10).withValues(alpha: .1),
            countdownEvenColor: ColorUtil.darken(Colors.blue.shade100, 10).withValues(alpha: .1),
            countdownOddBorderColor: ColorUtil.darken(Colors.blue.shade100, 10),
            countdownEvenBorderColor: ColorUtil.darken(Colors.blue.shade100, 10),
            countdownNumberColor: ColorUtil.darken(Colors.blue.shade50, 5),
            countdownUnitColor: ColorUtil.darken(Colors.blue.shade50, 5),
            useLightningEffectOnCountdown: false,
            firstArrowColor: ColorUtil.darken(Colors.blue.shade100, 5),
            secondArrowColor: ColorUtil.darken(Colors.blue.shade100, 25).withValues(alpha: .8),
          ),
          firstPageConfig: PageViewBasedFirstPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            openingTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            generalTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            firstSubScaffoldColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            firstSubScaffoldBorderColor: Colors.white,
            firstSubScaffoldBorderWidth: 2.5,
            secondSubScaffoldColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            secondSubScaffoldBorderColor: Colors.white,
            secondSubScaffoldBorderWidth: 2.5,
          ),
          secondPageConfig: PageViewBasedSecondPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            generalTextColor: ColorUtil.darken(Colors.blue.shade300, 40),
            brideDividingBorderWidth: 2,
            brideImageBorderWidth: 2,
            brideDividingLineWidth: 1,
            brideDividingBorderColor: ColorUtil.darken(Colors.blue.shade500, 40),
            brideImageFrameColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            brideImageFrameBorderColor: Colors.white,
            brideDividingLineColor: ColorUtil.darken(Colors.blue.shade500, 40),
            brideNameTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            brideFatherNameTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            brideMotherNameTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            groomDividingBorderWidth: 2,
            groomImageBorderWidth: 2,
            groomDividingLineWidth: 1,
            groomDividingBorderColor: ColorUtil.darken(Colors.blue.shade500, 40),
            groomImageFrameColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            groomImageFrameBorderColor: Colors.white,
            groomDividingLineColor: ColorUtil.darken(Colors.blue.shade500, 40),
            groomNameTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            groomFatherNameTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            groomMotherNameTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
          ),
          thirdPageConfig: PageViewBasedThirdPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            contractTitleColor: ColorUtil.darken(Colors.blue.shade500, 40),
            contractBaseTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            receptionTitleColor: ColorUtil.darken(Colors.blue.shade500, 40),
            receptionBaseTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            dividingLineWidth: 2,
            dividingLineColor: ColorUtil.darken(Colors.blue.shade500, 40),
            contractCountdownBorderWidth: 2.5,
            contractCountdownOddColor: ColorUtil.darken(
              Colors.blue.shade200,
              8,
            ).withValues(alpha: .2),
            contractCountdownEvenColor: ColorUtil.darken(
              Colors.blue.shade200,
              8,
            ).withValues(alpha: .2),
            contractCountdownOddBorderColor: Colors.white,
            contractCountdownEvenBorderColor: Colors.white,
            contractCountdownNumberColor: ColorUtil.darken(Colors.blue.shade500, 40),
            contractCountdownUnitColor: ColorUtil.darken(Colors.blue.shade500, 40),
            receptionCountdownBorderWidth: 2.5,
            receptionCountdownOddColor: ColorUtil.darken(
              Colors.blue.shade200,
              8,
            ).withValues(alpha: .2),
            receptionCountdownEvenColor: ColorUtil.darken(
              Colors.blue.shade200,
              8,
            ).withValues(alpha: .2),
            receptionCountdownOddBorderColor: Colors.white,
            receptionCountdownEvenBorderColor: Colors.white,
            receptionCountdownNumberColor: ColorUtil.darken(Colors.blue.shade500, 40),
            receptionCountdownUnitColor: ColorUtil.darken(Colors.blue.shade500, 40),
            useLightningEffectOnCountdown: false,
          ),
          thirdDifferentLocationPageConfig: PageViewBasedThirdDifferentLocationPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            dateTimeIconColor: ColorUtil.darken(Colors.blue.shade500, 40),
            dateTimeBaseTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            countdownBorderWidth: 2.5,
            countdownOddColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            countdownEvenColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            countdownOddBorderColor: Colors.white,
            countdownEvenBorderColor: Colors.white,
            countdownNumberColor: ColorUtil.darken(Colors.blue.shade500, 40),
            countdownUnitColor: ColorUtil.darken(Colors.blue.shade500, 40),
            useLightningEffectOnCountdown: false,
            dividingLineWidth: 2,
            dividingLineColor: ColorUtil.darken(Colors.blue.shade500, 40),
            placeIconColor: ColorUtil.darken(Colors.blue.shade500, 40),
            placeBaseTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            addressTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            mapsBorderColor: Colors.grey.shade400,
            getDirectionsButtonColor: ColorUtil.darken(
              Colors.blue.shade200,
              8,
            ).withValues(alpha: .2),
            getDirectionsButtonLabelColor: ColorUtil.darken(Colors.blue.shade500, 40),
            getDirectionsButtonBorderWidth: 2,
            getDirectionsButtonBorderColor: ColorUtil.darken(Colors.blue.shade500, 40),
          ),
          fourthPageConfig: PageViewBasedFourthPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            placeIconColor: ColorUtil.darken(Colors.blue.shade500, 40),
            placeTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            addressTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            dividingLineWidth: 2,
            dividingLineColor: ColorUtil.darken(Colors.blue.shade500, 40),
            mapsBorderColor: Colors.grey.shade400,
            getDirectionsButtonColor: ColorUtil.darken(
              Colors.blue.shade200,
              8,
            ).withValues(alpha: .2),
            getDirectionsButtonLabelColor: ColorUtil.darken(Colors.blue.shade500, 40),
            getDirectionsButtonBorderWidth: 2,
            getDirectionsButtonBorderColor: ColorUtil.darken(Colors.blue.shade500, 40),
          ),
          fourthDifferentLocationPageConfig: PageViewBasedFourthDifferentLocationPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            dateTimeIconColor: ColorUtil.darken(Colors.blue.shade500, 40),
            dateTimeBaseTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            countdownBorderWidth: 2.5,
            countdownOddColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            countdownEvenColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            countdownOddBorderColor: Colors.white,
            countdownEvenBorderColor: Colors.white,
            countdownNumberColor: ColorUtil.darken(Colors.blue.shade500, 40),
            countdownUnitColor: ColorUtil.darken(Colors.blue.shade500, 40),
            useLightningEffectOnCountdown: false,
            dividingLineWidth: 2,
            dividingLineColor: ColorUtil.darken(Colors.blue.shade500, 40),
            placeIconColor: ColorUtil.darken(Colors.blue.shade500, 40),
            placeBaseTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            addressTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            mapsBorderColor: Colors.grey.shade400,
            getDirectionsButtonColor: ColorUtil.darken(
              Colors.blue.shade200,
              8,
            ).withValues(alpha: .2),
            getDirectionsButtonLabelColor: ColorUtil.darken(Colors.blue.shade500, 40),
            getDirectionsButtonBorderWidth: 2,
            getDirectionsButtonBorderColor: ColorUtil.darken(Colors.blue.shade500, 40),
          ),
          fifthPageConfig: PageViewBasedFifthPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            dividingLineWidth: 1.5,
            dividingVerticalLineColor: ColorUtil.darken(Colors.blue.shade500, 40),
            dividingHorizontalLineColor: ColorUtil.darken(Colors.blue.shade500, 40),
            seeMoreButtonColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            seeMoreButtonLabelColor: ColorUtil.darken(Colors.blue.shade500, 40),
            seeMoreButtonBorderWidth: 2,
            seeMoreButtonBorderColor: ColorUtil.darken(Colors.blue.shade500, 40),
            bottomSheetHandleColor: Colors.grey.shade300,
            bottomSheetContentScaffoldColor: Colors.white.withValues(alpha: .75),
            bottomSheetBackgroundColor: ColorUtil.darken(
              Colors.blue.shade100,
              40,
            ).withValues(alpha: .95),
            bottomSheetCloseIconColor: Colors.grey.shade300,
          ),
          sixthPageConfig: PageViewBasedSixthPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            introductionTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            introductionColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            introductionBorderColor: Colors.white,
            introductionBorderWidth: 2.5,
            bankColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            bankBorderColor: Colors.white,
            bankBorderWidth: 2.5,
            bankTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            bankCopyBaseColor: ColorUtil.darken(Colors.blue.shade500, 40),
          ),
          seventhPageConfig: PageViewBasedSeventhPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            fieldTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            fieldLabelColor: ColorUtil.darken(Colors.blue.shade500, 40),
            fieldFillColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            fieldBorderColor: ColorUtil.darken(Colors.blue.shade500, 40),
            fieldSplashColor: ColorUtil.darken(Colors.blue.shade50, 10),
            overlayColor: ColorUtil.darken(Colors.blue.shade50, 5).withValues(alpha: .95),
            overlayBorderColor: Colors.white,
            dropdownItemSelectedColor: ColorUtil.darken(Colors.blue.shade100, 5),
            dropdownItemTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            dropdownItemSelectedTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            dropdownItemHoveredColor: ColorUtil.darken(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .95),
            // dropdownItemSplashColor: ColorUtil.darken(Colors.blue.shade100, 5),
            submitButtonColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            submitButtonLabelColor: ColorUtil.darken(Colors.blue.shade500, 40),
            submitButtonBorderWidth: 2,
            submitButtonBorderColor: ColorUtil.darken(Colors.blue.shade500, 40),
            rsvpBackgroundColor: ColorUtil.darken(Colors.blue.shade200, 8).withValues(alpha: .2),
            rsvpBorderColor: Colors.white,
            rsvpBorderWidth: 2.5,
            rsvpNameTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            rsvpTimeAgoTextColor: ColorUtil.darken(Colors.blue.shade400, 30),
            rsvpNameInstanceTextColor: ColorUtil.darken(Colors.blue.shade700, 40),
            rsvpAttendanceTextColorLighten: 5,
            rsvpMessageTextColor: ColorUtil.darken(Colors.blue.shade300, 40),
            seeMoreButtonColor: ColorUtil.darken(Colors.blue.shade50, 8).withValues(alpha: .2),
            seeMoreButtonLabelColor: ColorUtil.darken(Colors.blue.shade500, 40),
            seeMoreButtonBorderWidth: 2,
            seeMoreButtonBorderColor: ColorUtil.darken(Colors.blue.shade500, 40),
            bottomSheetHandleColor: Colors.grey.shade300,
            bottomSheetContentScaffoldColor: Colors.white.withValues(alpha: .75),
            bottomSheetBackgroundColor: ColorUtil.darken(
              Colors.blue.shade100,
              40,
            ).withValues(alpha: .95),
            bottomSheetCloseIconColor: Colors.grey.shade300,
          ),
          eighthPageConfig: PageViewBasedEighthPageConfig(
            useBackdropBlurOnScaffold: false,
            firstGradientScaffoldColor: Colors.white.withValues(alpha: .85),
            secondGradientScaffoldColor: ColorUtil.lighten(
              Colors.blue.shade50,
              10,
            ).withValues(alpha: .9),
            scaffoldBorder: GradientBoxBorder(
              width: 4,
              gradient: LinearGradient(
                begin: .topCenter,
                end: .bottomCenter,
                colors: [
                  ColorUtil.darken(Colors.blue.shade100, 10),
                  ColorUtil.darken(Colors.blue.shade300, 30),
                ],
                transform: const GradientRotation(-.2),
              ),
            ),
            useGlassEffectOnScaffold: false,
            titlePageColor: Colors.white,
            closingTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
            brideGroomNameColor: ColorUtil.darken(Colors.blue.shade500, 40),
            brandBackgroundColor: ColorUtil.lighten(Colors.blue.shade50, 10).withValues(alpha: .9),
            brandTextColor: ColorUtil.darken(Colors.blue.shade500, 40),
          ),
        ),
        initialPage: initialPage,
        useWrapper: useWrapper,
        invitationData: invitationData,
        brandProfile: brandProfile,
      ),
    );
  }
}
